// =========================================================
// EcoRoute — Bilingual layer (FR / AR)
// Lightweight, zero-dependency.
// =========================================================
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export const LANGS = {
  fr: { code: "fr", label: "FR", name: "Français", dir: "ltr" },
  en: { code: "en", label: "EN", name: "English", dir: "ltr" },
  ar: { code: "ar", label: "AR", name: "العربية", dir: "rtl" },
};

const STORAGE_KEY = "ecoroute.lang";

// Only the most visible strings are translated. The rest stays in French
// (the project's default).
const dict = {
  // ----- Sidebar / nav -----
  "nav.overview":     { fr: "Vue d'ensemble",  en: "Overview",       ar: "نظرة عامة" },
  "nav.planner":      { fr: "Planification",   en: "Planner",        ar: "التخطيط" },
  "nav.deliveries":   { fr: "Livraisons",      en: "Deliveries",     ar: "التسليمات" },
  "nav.fleet":        { fr: "Flotte",          en: "Fleet",          ar: "الأسطول" },
  "nav.analytics":    { fr: "Analytique",      en: "Analytics",      ar: "التحليلات" },
  "nav.alerts":       { fr: "Alertes",         en: "Alerts",         ar: "التنبيهات" },
  "nav.team":         { fr: "Équipe",          en: "Team",           ar: "الفريق" },
  "nav.menu":         { fr: "Menu",            en: "Menu",           ar: "القائمة" },
  "nav.search":       { fr: "Recherche rapide", en: "Quick search",  ar: "بحث سريع" },
  "nav.back":         { fr: "Retour à l'accueil", en: "Back to home", ar: "العودة إلى الرئيسية" },

  // ----- Topbar -----
  "topbar.console":   { fr: "Console opérateur", en: "Operator console", ar: "لوحة المشغل" },
  "topbar.alerts":    { fr: "Alertes",          en: "Alerts",         ar: "التنبيهات" },
  "topbar.demo":      { fr: "Démo live",        en: "Live demo",      ar: "عرض مباشر" },
  "topbar.morocco":   { fr: "Heure Maroc",      en: "Morocco time",   ar: "توقيت المغرب" },
  "topbar.fleet":     { fr: "Flotte",           en: "Fleet",          ar: "الأسطول" },
  "topbar.fleet.active": { fr: "actifs",        en: "active",         ar: "نشطة" },
  "topbar.lang":      { fr: "Langue",           en: "Language",       ar: "اللغة" },

  // ----- RouteBot CTA -----
  "bot.online":       { fr: "En ligne · prêt à aider", en: "Online · ready to help", ar: "متصل · جاهز للمساعدة" },

  // ----- Overview -----
  "ov.kpi.trucks":      { fr: "Camions en route",      en: "Trucks en route",   ar: "شاحنات في الطريق" },
  "ov.kpi.km":          { fr: "Km parcourus aujourd'hui", en: "Km driven today", ar: "كلم مقطوعة اليوم" },
  "ov.kpi.co2":         { fr: "CO₂ économisé (7j)",    en: "CO₂ saved (7d)",    ar: "CO₂ موفّر (٧أ)" },
  "ov.kpi.alerts":      { fr: "Alertes actives",       en: "Active alerts",     ar: "تنبيهات نشطة" },
  "ov.kpi.trucks.sub":  { fr: "tous dans la fenêtre",  en: "all on schedule",   ar: "كلها داخل النافذة" },
  "ov.kpi.km.sub":      { fr: "+18% vs hier",          en: "+18% vs yesterday", ar: "+١٨٪ مقابل أمس" },
  "ov.kpi.co2.sub":     { fr: "-23% vs baseline",      en: "-23% vs baseline",  ar: "-٢٣٪ مقابل المرجع" },
  "ov.kpi.alerts.sub":  { fr: "2 haute priorité",      en: "2 high priority",   ar: "٢ عالية الأولوية" },

  "ov.weather.title":   { fr: "Conditions actuelles",  en: "Current conditions", ar: "الظروف الحالية" },
  "ov.weather.eyebrow": { fr: "Météo flotte",          en: "Fleet weather",     ar: "الطقس على الأسطول" },
  "ov.activity.title":  { fr: "Fil d'opérations",      en: "Operations feed",   ar: "سجل العمليات" },
  "ov.activity.eyebrow": { fr: "Activité récente",     en: "Recent activity",   ar: "النشاط الأخير" },
  "ov.fleet.title":     { fr: "Camions en route",      en: "Trucks en route",   ar: "شاحنات في الطريق" },
  "ov.fleet.eyebrow":   { fr: "Flotte",                en: "Fleet",             ar: "الأسطول" },
  "ov.fleet.viewall":   { fr: "Voir tout",             en: "View all",          ar: "عرض الكل" },
  "ov.deliveries.title": { fr: "arrêts",               en: "stops",             ar: "محطات" },
  "ov.deliveries.eyebrow": { fr: "Livraisons du jour", en: "Today's deliveries", ar: "تسليمات اليوم" },
  "ov.deliveries.viewall": { fr: "Voir toutes les livraisons", en: "View all deliveries", ar: "عرض كل التسليمات" },

  // ----- Daily briefing -----
  "brief.eyebrow":      { fr: "Briefing IA · matinée", en: "AI briefing · morning", ar: "إحاطة الذكاء الاصطناعي · الصباح" },
  "brief.title":        { fr: "Votre matinée d'opérations en 3 points", en: "Your morning ops in 3 bullets", ar: "صباحك التشغيلي في ٣ نقاط" },
  "brief.subtitle":     { fr: "Généré par RouteBot à partir des données live", en: "Generated by RouteBot from live data", ar: "تم إنشاؤه بواسطة RouteBot من البيانات الحية" },
  "brief.priority":     { fr: "Priorité",              en: "Priority",          ar: "أولوية" },
  "brief.weather":      { fr: "Météo",                 en: "Weather",           ar: "الطقس" },
  "brief.action":       { fr: "Action",                en: "Action",            ar: "إجراء" },
  "brief.refresh":      { fr: "Actualiser",            en: "Refresh",           ar: "تحديث" },

  // ----- Planner -----
  "pl.eyebrow":         { fr: "Nouveau trajet",        en: "New route",         ar: "رحلة جديدة" },
  "pl.title.1":         { fr: "Planifier",             en: "Plan",              ar: "تخطيط" },
  "pl.title.2":         { fr: "une livraison",         en: "a delivery",        ar: "تسليم" },
  "pl.intro":           { fr: "Sélectionnez un départ, une destination, et ajoutez des arrêts intermédiaires.", en: "Pick a start, a destination, and add intermediate stops.", ar: "اختر نقطة الانطلاق والوجهة، وأضف محطات وسيطة." },
  "pl.start":           { fr: "Départ",                en: "Start",             ar: "الانطلاق" },
  "pl.destination":     { fr: "Destination",           en: "Destination",       ar: "الوجهة" },
  "pl.stop":            { fr: "Arrêt",                 en: "Stop",              ar: "محطة" },
  "pl.add.stop":        { fr: "Ajouter un arrêt",      en: "Add a stop",        ar: "إضافة محطة" },
  "pl.swap":            { fr: "Inverser",              en: "Swap",              ar: "تبديل" },
  "pl.mode":            { fr: "Mode d'optimisation",   en: "Optimization mode", ar: "وضع التحسين" },
  "pl.optimize":        { fr: "Calculer l'itinéraire", en: "Calculate route",   ar: "حساب المسار" },
  "pl.optimizing":      { fr: "Calcul en cours…",      en: "Calculating…",      ar: "جارٍ الحساب…" },
  "pl.clear":           { fr: "Effacer",               en: "Clear",             ar: "مسح" },

  // ----- Explainability -----
  "exp.eyebrow":        { fr: "Explication IA",        en: "AI explanation",    ar: "تفسير الذكاء الاصطناعي" },
  "exp.title":          { fr: "Comment cette route a été choisie", en: "How this route was chosen", ar: "كيف تم اختيار هذا المسار" },
  "exp.subtitle":       { fr: "Pondération des facteurs analysés par l'IA pour ce trajet.", en: "Weighting of factors the AI analyzed for this trip.", ar: "ترجيح العوامل التي حللها الذكاء الاصطناعي لهذه الرحلة." },
  "exp.factor.distance": { fr: "Distance & géométrie", en: "Distance & geometry", ar: "المسافة والهندسة" },
  "exp.factor.traffic": { fr: "Trafic & congestion",   en: "Traffic & congestion", ar: "حركة المرور والازدحام" },
  "exp.factor.weather": { fr: "Météo",                 en: "Weather",           ar: "الطقس" },
  "exp.factor.demand":  { fr: "Demande client",        en: "Customer demand",   ar: "طلب الزبائن" },
  "exp.factor.fuel":    { fr: "Carburant & coût",      en: "Fuel & cost",       ar: "الوقود والتكلفة" },

  // ----- Indicators (KPI strip + tiles) -----
  "kpi.title":          { fr: "Indicateurs",           en: "Indicators",        ar: "المؤشرات" },
  "kpi.distance":       { fr: "Distance",              en: "Distance",          ar: "المسافة" },
  "kpi.duration":       { fr: "Durée",                 en: "Duration",          ar: "المدة" },
  "kpi.duration.full":  { fr: "Durée estimée",         en: "Estimated time",    ar: "المدة المقدرة" },
  "kpi.fuel":           { fr: "Carburant",             en: "Fuel",              ar: "الوقود" },
  "kpi.fuel.saved":     { fr: "Carburant économisé",   en: "Fuel saved",        ar: "الوقود الموفّر" },
  "kpi.cost":           { fr: "Coût",                  en: "Cost",              ar: "التكلفة" },
  "kpi.cost.saved":     { fr: "Économie MAD",          en: "MAD saved",         ar: "توفير MAD" },
  "kpi.co2":            { fr: "CO₂",                   en: "CO₂",               ar: "CO₂" },
  "kpi.co2.emitted":    { fr: "CO₂ émis",              en: "CO₂ emitted",       ar: "CO₂ المنبعث" },
  "kpi.risk":           { fr: "Risque",                en: "Risk",              ar: "الخطر" },
  "kpi.risk.delay":     { fr: "Risque retard",         en: "Delay risk",        ar: "خطر التأخير" },
  "kpi.savings":        { fr: "Économies",             en: "Savings",           ar: "التوفير" },
  "kpi.savings.vs":     { fr: "Économies vs trajet rapide", en: "Savings vs fastest route", ar: "التوفير مقابل أسرع مسار" },

  // ----- Risk levels -----
  "risk.low":           { fr: "Faible",                en: "Low",               ar: "منخفض" },
  "risk.medium":        { fr: "Moyen",                 en: "Medium",            ar: "متوسط" },
  "risk.high":          { fr: "Élevé",                 en: "High",              ar: "مرتفع" },

  // ----- Modes -----
  "mode.ai":            { fr: "IA optimisée",          en: "AI optimized",      ar: "محسّن بالذكاء الاصطناعي" },
  "mode.ai.short":      { fr: "IA",                    en: "AI",                ar: "ذكاء" },
  "mode.ai.desc":       { fr: "Compromis intelligent distance / durée / carburant.", en: "Smart compromise of distance, time, and fuel.", ar: "توازن ذكي بين المسافة والوقت والوقود." },
  "mode.eco":           { fr: "Mode éco",              en: "Eco mode",          ar: "الوضع البيئي" },
  "mode.eco.short":     { fr: "Éco",                   en: "Eco",               ar: "بيئي" },
  "mode.eco.desc":      { fr: "Réduit la consommation et les émissions.", en: "Cuts consumption and emissions.", ar: "يقلل الاستهلاك والانبعاثات." },
  "mode.classic":       { fr: "Trajet rapide",         en: "Fast route",        ar: "مسار سريع" },
  "mode.classic.short": { fr: "Rapide",                en: "Fast",              ar: "سريع" },
  "mode.classic.desc":  { fr: "Priorité à la durée totale du trajet.", en: "Prioritizes overall trip time.", ar: "الأولوية لمدة الرحلة الكلية." },

  // ----- AI decision card -----
  "ai.decision":        { fr: "Décision IA",           en: "AI decision",       ar: "قرار الذكاء الاصطناعي" },
  "ai.risk":            { fr: "Risque",                en: "Risk",              ar: "الخطر" },
  "ai.mode.chosen":     { fr: "Mode choisi par l'IA",  en: "Mode chosen by AI", ar: "الوضع الذي اختاره الذكاء الاصطناعي" },
  "ai.mode.applied":    { fr: "Mode appliqué",         en: "Applied mode",      ar: "الوضع المطبق" },
  "ai.live.context":    { fr: "Données temps réel utilisées", en: "Live data used", ar: "البيانات الحية المستخدمة" },
  "ai.user.override":   { fr: "Vous avez forcé",       en: "You forced",        ar: "لقد فرضت" },
  "ai.user.override.tail": { fr: ". Le choix utilisateur est conservé. Passez en", en: ". Your choice is kept. Switch to", ar: ". خيارك محفوظ. انتقل إلى" },
  "ai.user.override.suffix": { fr: "pour laisser l'IA décider.", en: "to let the AI decide.", ar: "لترك الذكاء الاصطناعي يقرر." },
  "ai.traffic.unavailable": { fr: "indisponible",      en: "unavailable",       ar: "غير متاح" },

  // ----- Map overlay -----
  "map.from":           { fr: "Départ",                en: "Start",             ar: "الانطلاق" },
  "map.to":             { fr: "Arrivée",               en: "Arrival",           ar: "الوصول" },
  "map.summary":        { fr: "Indicateurs calculés",  en: "Calculated indicators", ar: "المؤشرات المحسوبة" },

  // ----- Analytics -----
  "an.eyebrow":         { fr: "Analytique",            en: "Analytics",         ar: "التحليلات" },
  "an.title.1":         { fr: "Mesurer l'impact,",     en: "Measure impact,",   ar: "قِس الأثر،" },
  "an.title.2":         { fr: "piloter la décision.",  en: "drive the decision.", ar: "وقُد القرار." },
  "an.subtitle":        { fr: "Vue complète de la performance : CO₂, coût, carburant, livraisons, utilisation des modes.", en: "Full performance view: CO₂, cost, fuel, deliveries, mode usage.", ar: "نظرة شاملة على الأداء: CO₂، التكلفة، الوقود، التسليمات، استخدام الأوضاع." },
  "an.range.7d":        { fr: "7j",                    en: "7d",                ar: "٧أ" },
  "an.range.30d":       { fr: "30j",                   en: "30d",               ar: "٣٠أ" },
  "an.range.90d":       { fr: "90j",                   en: "90d",               ar: "٩٠أ" },
  "an.kpi.co2":         { fr: "CO₂ total",             en: "Total CO₂",         ar: "إجمالي CO₂" },
  "an.kpi.cost":        { fr: "Coût total",            en: "Total cost",        ar: "التكلفة الإجمالية" },
  "an.kpi.deliveries":  { fr: "Livraisons",            en: "Deliveries",        ar: "التسليمات" },
  "an.kpi.km":          { fr: "Km parcourus",          en: "Km driven",         ar: "كلم مقطوعة" },
  "an.kpi.co2.sub":     { fr: "-23% vs semaine dernière", en: "-23% vs last week", ar: "-٢٣٪ مقابل الأسبوع الماضي" },
  "an.kpi.cost.sub":    { fr: "-18% grâce à l'IA",     en: "-18% thanks to AI", ar: "-١٨٪ بفضل الذكاء الاصطناعي" },
  "an.kpi.deliveries.sub": { fr: "+12% vs période",    en: "+12% vs period",    ar: "+١٢٪ مقابل الفترة" },
  "an.kpi.km.sub":      { fr: "rendement 82%",         en: "82% efficiency",    ar: "كفاءة ٨٢٪" },

  "an.trend.title":     { fr: "Tendance hebdomadaire", en: "Weekly trend",      ar: "الاتجاه الأسبوعي" },
  "an.trend.subtitle":  { fr: "CO₂ et coût opérationnel jour par jour", en: "CO₂ and operating cost day by day", ar: "CO₂ والتكلفة التشغيلية يومًا بيوم" },

  "an.heatmap.title":   { fr: "Charge de livraisons", en: "Delivery load",     ar: "حمل التسليمات" },
  "an.heatmap.label":   { fr: "Livraisons par jour",  en: "Deliveries per day", ar: "التسليمات اليومية" },
  "an.heatmap.subtitle": { fr: "Repérez les jours les plus intenses de la semaine.", en: "Spot the busiest days of the week.", ar: "تعرّف على أكثر الأيام ازدحامًا." },

  "an.eff.eyebrow":     { fr: "Efficacité",            en: "Efficiency",        ar: "الكفاءة" },
  "an.eff.title":       { fr: "Coût moyen par livraison", en: "Avg cost per delivery", ar: "متوسط التكلفة لكل تسليم" },
  "an.eff.best":        { fr: "Meilleur jour",         en: "Best day",          ar: "أفضل يوم" },
  "an.eff.worst":       { fr: "Plus coûteux",          en: "Most expensive",    ar: "الأغلى" },

  "an.gauges.eyebrow":  { fr: "Indicateurs clés",      en: "Key indicators",    ar: "المؤشرات الرئيسية" },
  "an.gauges.title":    { fr: "Santé opérationnelle",  en: "Operational health", ar: "الصحة التشغيلية" },
  "an.gauges.fleet":    { fr: "Utilisation flotte",    en: "Fleet utilization", ar: "استخدام الأسطول" },
  "an.gauges.ontime":   { fr: "Livraisons à l'heure",  en: "On-time deliveries", ar: "التسليمات في الموعد" },
  "an.gauges.fuel":     { fr: "Score carburant",       en: "Fuel score",        ar: "نقاط الوقود" },
  "an.gauges.ai":       { fr: "Adoption IA",           en: "AI adoption",       ar: "اعتماد الذكاء الاصطناعي" },

  "an.modes.title":     { fr: "Performance par mode",  en: "Performance by mode", ar: "الأداء حسب الوضع" },
  "an.modes.subtitle":  { fr: "Part d'utilisation des trois modes d'optimisation.", en: "Share of use across the three optimization modes.", ar: "حصة استخدام أوضاع التحسين الثلاثة." },

  "an.compare.eyebrow": { fr: "Trajet courant",        en: "Current trip",      ar: "الرحلة الحالية" },
  "an.compare.title":   { fr: "Comparaison vs baseline rapide", en: "Comparison vs fast baseline", ar: "مقارنة مع الأساس السريع" },
  "an.compare.current": { fr: "Actuel",                en: "Current",           ar: "الحالي" },
  "an.compare.baseline": { fr: "Baseline",             en: "Baseline",          ar: "الأساس" },

  "an.equiv.eyebrow":   { fr: "Équivalences",          en: "Equivalents",       ar: "ما يعادل" },
  "an.equiv.title":     { fr: "Ce que 142 kg de CO₂ évités représentent", en: "What 142 kg of CO₂ avoided means", ar: "ماذا يعني تجنب ١٤٢ كغ من CO₂" },
  "an.equiv.trees":     { fr: "arbres plantés · compensation annuelle", en: "trees planted · yearly offset", ar: "أشجار مزروعة · تعويض سنوي" },
  "an.equiv.fuel":      { fr: "carburant économisé",   en: "fuel saved",        ar: "وقود موفّر" },
  "an.equiv.budget":    { fr: "budget opérationnel évité", en: "operating budget avoided", ar: "ميزانية تشغيلية متجنبة" },
};

const LanguageContext = createContext({
  lang: "fr",
  setLang: () => {},
  t: (k) => k,
  dir: "ltr",
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    if (typeof window === "undefined") return "fr";
    const stored = window.localStorage?.getItem(STORAGE_KEY);
    return stored && LANGS[stored] ? stored : "fr";
  });

  const setLang = useCallback((next) => {
    if (!LANGS[next]) return;
    setLangState(next);
    try {
      window.localStorage?.setItem(STORAGE_KEY, next);
    } catch {
      /* noop */
    }
  }, []);

  // Reflect language + direction on <html>. RTL flips the whole sidebar
  // layout for Arabic; we keep the rest of the component CSS untouched.
  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = lang;
    document.documentElement.dir = LANGS[lang].dir;
  }, [lang]);

  const value = useMemo(() => {
    function t(key, fallback) {
      const entry = dict[key];
      if (!entry) return fallback ?? key;
      return entry[lang] ?? entry.fr ?? fallback ?? key;
    }
    return { lang, setLang, t, dir: LANGS[lang].dir };
  }, [lang, setLang]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export function useT() {
  return useContext(LanguageContext).t;
}
