// Données statiques / simulées utilisées par l'interface EcoRoute.
// L'ordre [lng, lat] correspond à la convention du backend.

export const CITIES = {
  Tanger: { coords: [-5.8137, 35.7595], region: "Nord" },
  Tetouan: { coords: [-5.3684, 35.5785], region: "Nord" },
  Nador: { coords: [-2.9287, 35.1681], region: "Oriental" },
  Oujda: { coords: [-1.9293, 34.6814], region: "Oriental" },
  Kenitra: { coords: [-6.5802, 34.261], region: "Nord-Ouest" },
  Rabat: { coords: [-6.8498, 34.0209], region: "Centre" },
  Casablanca: { coords: [-7.5898, 33.5731], region: "Centre" },
  Mohammedia: { coords: [-7.3833, 33.6833], region: "Centre" },
  ElJadida: { coords: [-8.5, 33.2333], region: "Centre" },
  Fes: { coords: [-5.0078, 34.0331], region: "Centre-Nord" },
  Meknes: { coords: [-5.5473, 33.8935], region: "Centre-Nord" },
  Marrakech: { coords: [-7.9811, 31.6295], region: "Sud" },
  BeniMellal: { coords: [-6.3498, 32.3373], region: "Centre" },
  Agadir: { coords: [-9.5981, 30.4278], region: "Sud" },
  Essaouira: { coords: [-9.7697, 31.5085], region: "Sud" },
  Ouarzazate: { coords: [-6.9094, 30.9335], region: "Sud-Est" },
  Errachidia: { coords: [-4.428, 31.9314], region: "Sud-Est" },
  Laayoune: { coords: [-13.2033, 27.1536], region: "Sahara" },
};

export const CITY_KEYS = Object.keys(CITIES);

export const CITY_LABELS = {
  Tanger: "Tanger",
  Tetouan: "Tétouan",
  Nador: "Nador",
  Oujda: "Oujda",
  Kenitra: "Kénitra",
  Rabat: "Rabat",
  Casablanca: "Casablanca",
  Mohammedia: "Mohammédia",
  ElJadida: "El Jadida",
  Fes: "Fès",
  Meknes: "Meknès",
  Marrakech: "Marrakech",
  BeniMellal: "Béni Mellal",
  Agadir: "Agadir",
  Essaouira: "Essaouira",
  Ouarzazate: "Ouarzazate",
  Errachidia: "Errachidia",
  Laayoune: "Laâyoune",
};

export const MODES = [
  { id: "ai", label: "IA optimisée", hint: "Meilleur compromis coût / délai / CO₂" },
  { id: "eco", label: "Éco", hint: "Priorité émissions et carburant" },
  { id: "fast", label: "Rapide", hint: "Priorité délai de livraison" },
];

export const SCENARIOS = [
  { id: "standard", label: "Standard" },
  { id: "urgent", label: "Urgent" },
  { id: "fragile", label: "Fragile" },
  { id: "frigo", label: "Chaîne du froid" },
];

// Flotte simulée
export const FLEET = [
  {
    id: "TRK-014",
    plate: "12345-A-6",
    driver: "Youssef Benali",
    type: "Semi-remorque",
    capacityT: 24,
    status: "En route",
    fuelPct: 62,
    loadPct: 78,
    location: "Casablanca → Marrakech",
    km: 412,
  },
  {
    id: "TRK-022",
    plate: "98421-B-7",
    driver: "Salma El Idrissi",
    type: "Camion 19t",
    capacityT: 19,
    status: "Chargement",
    fuelPct: 94,
    loadPct: 35,
    location: "Hub Rabat",
    km: 12,
  },
  {
    id: "TRK-031",
    plate: "55208-C-1",
    driver: "Omar Lahlou",
    type: "Fourgon 3.5t",
    capacityT: 3.5,
    status: "Disponible",
    fuelPct: 81,
    loadPct: 0,
    location: "Dépôt Casablanca",
    km: 0,
  },
  {
    id: "TRK-045",
    plate: "73610-D-4",
    driver: "Nadia Amrani",
    type: "Frigorifique 12t",
    capacityT: 12,
    status: "En route",
    fuelPct: 48,
    loadPct: 92,
    location: "Agadir → Casablanca",
    km: 287,
  },
  {
    id: "TRK-058",
    plate: "41072-E-9",
    driver: "Khalid Ziani",
    type: "Semi-remorque",
    capacityT: 24,
    status: "Maintenance",
    fuelPct: 20,
    loadPct: 0,
    location: "Atelier Mohammédia",
    km: 0,
  },
  {
    id: "TRK-063",
    plate: "38901-F-2",
    driver: "Leïla Bouzid",
    type: "Camion 19t",
    capacityT: 19,
    status: "En route",
    fuelPct: 71,
    loadPct: 66,
    location: "Fès → Tanger",
    km: 198,
  },
];

// Expéditions simulées
export const SHIPMENTS = [
  {
    id: "EXP-2041",
    client: "Marjane Holding",
    from: "Casablanca",
    to: "Marrakech",
    weightT: 18.2,
    status: "En route",
    eta: "14:20",
    priority: "Normale",
    truck: "TRK-014",
    progress: 62,
  },
  {
    id: "EXP-2042",
    client: "OCP Group",
    from: "Casablanca",
    to: "Agadir",
    weightT: 22.8,
    status: "Planifié",
    eta: "18:45",
    priority: "Haute",
    truck: "TRK-058",
    progress: 0,
  },
  {
    id: "EXP-2043",
    client: "Label'Vie",
    from: "Rabat",
    to: "Fès",
    weightT: 11.4,
    status: "Chargement",
    eta: "11:10",
    priority: "Normale",
    truck: "TRK-022",
    progress: 5,
  },
  {
    id: "EXP-2044",
    client: "Cosumar",
    from: "Agadir",
    to: "Casablanca",
    weightT: 10.9,
    status: "En route",
    eta: "16:55",
    priority: "Haute",
    truck: "TRK-045",
    progress: 74,
  },
  {
    id: "EXP-2045",
    client: "Aswak Assalam",
    from: "Fes",
    to: "Tanger",
    weightT: 7.6,
    status: "En route",
    eta: "15:30",
    priority: "Normale",
    truck: "TRK-063",
    progress: 48,
  },
  {
    id: "EXP-2046",
    client: "Carrefour Maroc",
    from: "Casablanca",
    to: "Tanger",
    weightT: 15.0,
    status: "Livré",
    eta: "09:05",
    priority: "Normale",
    truck: "TRK-014",
    progress: 100,
  },
  {
    id: "EXP-2047",
    client: "Renault Maroc",
    from: "Tanger",
    to: "Casablanca",
    weightT: 19.7,
    status: "Retardé",
    eta: "17:40",
    priority: "Haute",
    truck: "TRK-063",
    progress: 28,
  },
];

// Alertes simulées
export const ALERTS = [
  {
    id: 1,
    level: "critique",
    title: "Incident sur A7",
    message: "Accident signalé km 142 direction Marrakech. Déviation recommandée.",
    time: "Il y a 8 min",
    zone: "Casablanca → Marrakech",
  },
  {
    id: 2,
    level: "avertissement",
    title: "Congestion urbaine",
    message: "Trafic dense à l'entrée de Casablanca (sortie Aïn Sebaâ).",
    time: "Il y a 22 min",
    zone: "Casablanca",
  },
  {
    id: 3,
    level: "info",
    title: "Météo défavorable",
    message: "Rafales de vent 45 km/h prévues sur l'axe Agadir — Essaouira.",
    time: "Il y a 1 h",
    zone: "Sud",
  },
  {
    id: 4,
    level: "info",
    title: "Maintenance planifiée",
    message: "TRK-058 en atelier jusqu'à 18:00.",
    time: "Il y a 2 h",
    zone: "Mohammédia",
  },
];

// KPI mensuels simulés
export const MONTHLY_KPIS = [
  { month: "Jan", livraisons: 412, co2: 38.2, cout: 412000 },
  { month: "Fév", livraisons: 438, co2: 40.1, cout: 428000 },
  { month: "Mar", livraisons: 471, co2: 42.9, cout: 465000 },
  { month: "Avr", livraisons: 502, co2: 41.5, cout: 488000 },
  { month: "Mai", livraisons: 528, co2: 39.8, cout: 502000 },
  { month: "Juin", livraisons: 561, co2: 38.4, cout: 518000 },
  { month: "Juil", livraisons: 589, co2: 37.2, cout: 535000 },
  { month: "Aoû", livraisons: 612, co2: 36.1, cout: 549000 },
];

export const STATUS_COLORS = {
  "En route": "bg-emerald-50 text-emerald-700 ring-emerald-200",
  Planifié: "bg-slate-50 text-slate-700 ring-slate-200",
  Chargement: "bg-amber-50 text-amber-700 ring-amber-200",
  Livré: "bg-sky-50 text-sky-700 ring-sky-200",
  Retardé: "bg-rose-50 text-rose-700 ring-rose-200",
  Disponible: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  Maintenance: "bg-slate-50 text-slate-500 ring-slate-200",
};

export const PRIORITY_COLORS = {
  Haute: "bg-rose-50 text-rose-700 ring-rose-200",
  Normale: "bg-slate-50 text-slate-600 ring-slate-200",
  Basse: "bg-slate-50 text-slate-500 ring-slate-200",
};
